version: '3'

services:
  api:
    build: ./api/.
    image: "welldigital/callme:api-latest"
    ports: 
      - "7777:7777"
    environment:
      - CALLME_CONNECTION_STRING=root:callme@tcp(db:3306)/callme?parseTime=true&multiStatements=true
    depends_on:
      - "db"
  worker:
    build: ./worker/.
    image: "welldigital/callme:worker-latest"
    ports: 
      - "6666:6666"
    environment:
      - CALLME_CONNECTION_STRING=root:callme@tcp(db:3306)/callme?parseTime=true&multiStatements=true
    depends_on:
      - "db"
  db:
    image: "mysql:5.6"
    expose:
      - "3306"
    ports:
      - "6612:3306"
    volumes:
      - ./mysql/migrations/create/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=callme
  prometheus:
    image: "prom/prometheus:v2.0.0"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/:ro
