version: '3'

services:
  cmd:
    build: .
    image: "welldigital/callme:latest"
    ports: 
      - "6666:6666"
    environment:
      - CALLME_CONNECTION_STRING=root:callme@tcp(db:3306)/callme?parseTime=true&multiStatements=true
    depends_on:
      - "db"
  db:
    image: "mysql:5.6"
    expose:  
      - "3306"
    ports:
      - "6612:3306"
    volumes:
      - ./mysql/migrations/create/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=callme
  prometheus:
    image: "prom/prometheus:v2.0.0"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/:ro
    #environment:
      # "-config.file=/etc/prometheus/prometheus.yml", \
      # "-storage.local.path=/prometheus", \
      # "-web.console.templates=/etc/prometheus/consoles", \
      # "-web.console.libraries=/etc/prometheus/console_libraries", \
      # "-web.external-url=http://localhost:9090/prometheus" ]