version: 2
jobs:
  build:
    docker:
      - image: welldigital/golang-build:latest
        environment:
          GOPATH: /go
    working_directory: /go/src/github.com/welldigital/callme
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install
          command: make install
      - run:
          name: Build
          command: make docker-build
      - deploy:
          name: Push application Docker images
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              eval $(aws ecr get-login --region eu-west-2 --no-include-email)

              docker tag welldigital/callme:worker-latest ${ECR_ENDPOINT}/callme:worker-${CIRCLE_SHA1}
              docker tag welldigital/callme:worker-latest ${ECR_ENDPOINT}/callme:worker-latest
              docker push ${ECR_ENDPOINT}/callme:worker-${CIRCLE_SHA1}
              docker push ${ECR_ENDPOINT}/callme:worker-latest

              docker tag welldigital/callme:api-latest "${ECR_ENDPOINT}/callme:api-${CIRCLE_SHA1}
              docker tag welldigital/callme:api-latest "${ECR_ENDPOINT}/callme:api-latest
              docker push ${ECR_ENDPOINT}/callme:api-${CIRCLE_SHA1}
              docker push ${ECR_ENDPOINT}/callme:api-latest
            fi
      