version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9.2
    working_directory: ~/go/src/github.com/welldigital/callme
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install
          command: make install
      - run:
          name: Build
          command: make docker-build
      